AWSTemplateFormatVersion: '2010-09-09'
Description: LAMP stack EC2 deployment with security group and user data

Resources:
  LampInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316 # Replace with latest Ubuntu AMI for your region
      KeyName: your-key-name
      SecurityGroups: 
        - !Ref LampSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt update -y
          apt install -y apache2 php libapache2-mod-php mariadb-client unzip
          systemctl start apache2
          systemctl enable apache2

  LampSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH, HTTP, and HTTPS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
